{% set name = "qcfractal" %}
{% set version = "0.58" %}
# pattern for unpublished commits {% set version = "0.50b13.post52+gbb2748c85" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  # unpublished - any repo commit. sync commit in git_rev below with commit and distance in version above
  #git_url: https://github.com/MolSSI/QCFractal.git
  #git_rev: bb2748c8534b267e33f894ef71a2d9a6da50c5af
  #sha256: 81cdc093dda5e7739496088b70be7c3110fb691b4fdf22c7e3b58377450e2081
  # published tags.
  - url: https://pypi.org/packages/source/q/qcportal/qcportal-{{ version }}.tar.gz
    sha256: a7517012a4c3b722b89ecedc218f2359b63e1895c85185de517a3f63dfdfa657
    folder: qcportal
  - url: https://pypi.org/packages/source/q/qcfractalcompute/qcfractalcompute-{{ version }}.tar.gz
    sha256: e08d8c1acdb5b09d66b52fbe918c28ca696bd32b4494de6a1d6a9f77718bbe76
    folder: qcfractalcompute
  - url: https://pypi.org/packages/source/q/qcfractal/qcfractal-{{ version }}.tar.gz
    sha256: f76481548bde2201aeb99443cb3450d7236cbfdcc7995b7f6a2ac2e2749386d3
    folder: qcfractal
  - url: https://pypi.org/packages/source/q/qcarchivetesting/qcarchivetesting-{{ version }}.tar.gz
    sha256: 45b099cfec558ab0fb7373a3c2d1295b20ac5f2e4607e8af23f7182a9fce4c35
    folder: qcarchivetesting

build:
  number: 0
  noarch: python

outputs:
  - name: qcportal
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcportal
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >={{ python_min }}
        - numpy
        - msgpack-python
        - requests
        - pyyaml
        - pydantic >=1.10,<3.0a0
        - zstandard
        - apsw >=3.42
        - qcelemental <0.70a0
        - tabulate
        - tqdm
        - pandas
        - pyjwt >=2.10
        - packaging
        - typing_extensions
        - python-dateutil
        - pytz
    test:
      imports:
        - qcportal
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - test -f $SP_DIR/qcportal/__init__.py
        - pip check
        - python -c "import qcportal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    about:
      summary: Python library for interacting with QCArchive/QCFractal servers

  - name: qcfractalcompute
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcfractalcompute
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >={{ python_min }}
        - qcportal ={{ version }}
        - parsl
    test:
      imports:
        - qcfractalcompute
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - test -f $SP_DIR/qcfractalcompute/__init__.py
        - pip check
        - python -c "import qcfractalcompute as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
        - qcfractal-compute-manager --help
    about:
      summary: Distributed worker package for QCArchive

  - name: qcfractal
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcfractal
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >={{ python_min }}
        - flask
        - flask-jwt-extended
        - waitress
        - bcrypt
        - sqlalchemy >=2.0
        - alembic
        - psycopg2
        - geoip2
        - boto3
        - torsiondrive
        - qcmanybody
        - geometric >=1.1

        - qcfractalcompute ={{ version }}
        - __unix  # [unix]
    test:
      imports:
        - qcfractal.snowflake
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - test -f $SP_DIR/qcfractal/__init__.py
        - pip check
        - python -c "import qcfractal as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
        - qcfractal-server --help
    about:
      summary: Database and Web API for the QCArchive project

  - name: qcarchivetesting
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./qcarchivetesting
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=61.0
        - versioningit
      run:
        - python >={{ python_min }}
        - qcfractal ={{ version }}
        - qcengine <0.70a0
        - pytest
    test:
      imports:
        - qcarchivetesting.helpers
      requires:
        - python {{ python_min }}
        - pip
      commands:
        - test -f $SP_DIR/qcarchivetesting/__init__.py
        - pip check
        - python -c "import qcarchivetesting as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    about:
      summary: Additional testing fixtures and functions for the QCArchive project

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://molssi.github.io/QCFractal/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/main/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/license/bsd-3-clause/
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
  feedstock-name: qcfractal
  recipe-maintainers:
    - lnaden
    - bennybp
